name: Build binaries

on:
  push:
    tags:
      - "v*"

jobs:

  build:

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - run: pyinstaller vanonymizer.spec

      - uses: actions/upload-artifact@v4
        with:
          name: vanonymizer-${{ runner.os }}
          path: dist/
